@extends('layout.app')

@section('title', 'AI Detector')

@section('content')
    {{-- Welcome --}}
    <section class="flex flex-col-reverse md:flex-row justify-between">
        <div class="mt-8">
            <h1 class="text-5xl max-w-lg leading-snug text-center md:text-left">Welcome to <span
                    class="text-orange-500">CensorAI</span>, your
                guardian
                against
                AI-generated content</h1>
            <p class="max-w-lg text-gray-500 mt-5 text-center leading-snug md:text-left">Detecting AI's craft, ensuring
                content
                authenticity.
                Unveiling the unseen, guarding against AI-generated narratives.</p>
            <a href="https://drive.google.com/file/d/1SIpBg7kUF4UOjsluPl8b-8fvzl3J8exg/view?usp=sharing">
                <div class="flex flex-col mt-8 space-x-2 md:flex-row items-center ">
                    <img src="{{ asset('img/google.png') }}" class="w-1/3 h-1/3 mb-2 md:w-1/4 " alt="Google">
                    <img src="{{ asset('img/apple.png') }}" class="w-1/3 h-1/3 md:w-1/4 " alt="Apple">
                </div>
            </a>

            <div class="mt-8">
                <img src="{{ asset('img/decoration.png') }}" class="w-1/5 h-1/4 " alt="">
            </div>
        </div>
        <div>
            <img src="{{ asset('img/ai.png') }}" alt="" class="max-w-md">
        </div>

    </section>
    {{-- end  --}}

    {{-- start detect --}}
    @php
        $appear = false;
    @endphp
    <section class="mt-12">
        <h1 class="text-5xl text-center" id="detect">
            AI Content Detector
        </h1>
        @if ($appear)
            <input id="slider" type="range" min="0" max="100" step="1" value="50" readonly
                class="w-full bg-blue-500 mt-10  h-3 rounded-md" disabled oninput="updateSliderValue(this.value)">
        @endif
        {{-- {{ route('result') }} --}}
        <form method="GET" action="{{ route('result') }}">
            @csrf <!-- Add the CSRF token for security -->
            <div class="flex flex-col mt-10 md:flex-row justify-around  lg:items-center md:text-left ">
                <div class="flex flex-col max-w-lg md:max-w-xs lg:max-w-md ">
                    <h4 class="hidden text-3xl font-medium mb-5 md:block">AI Detector</h4>
                    <p class="text-center md:text-left">If your content appears to be entirely generated by AI, it could
                        impact its
                        search
                        engine ranking.
                        Utilize our free detector to analyze your content and make necessary adjustments before publishing
                    </p>
                </div>
                <textarea name="detector" required id="detector" rows="15" placeholder="Paste text or write here"
                    class="border-gray-300 border shadow-2xl p-3 mt-5 resize-none h-1/2 md:w-1/2"></textarea>
            </div>
            <div class="flex items-center justify-center mt-12">

                <button type="submit" class="bg-orange-500 text-white p-2 px-5 rounded-lg">
                    Analyze Text
                </button>
            </div>
            <div>
        </form>

        </div>

        <script>
            function updateSliderValue(value) {

                const sliderValue = document.getElementById('sliderValue');
                const sliderFill = document.getElementById('sliderFill');

                sliderValue.textContent = value;
                sliderFill.style.width = `${value}%`;
            }
        </script>
    </section>
@endsection
